### ISSUE TITLE
Duplicate issue - escaped strings get unescaped.

### ISSUE THREAD

**Issue by frankforte** [vlucas/jscompress.com#4]
```javascript
if (!noquotes) {
        string = string.replace(/"/g, '&quot;');
    }
```
gets replaced with

```javascript
if (!noquotes) {
        string = string.replace(/"/g,""");
    }
```
This is completely broken! &amp;quot; should be left alone. a double quote is not a minified version of an escaped quote, they are two different things!

**Comment by vlucas** [comment]
This has been fixed (finally) with a full rewrite in React.js: http://jscompress.com/
