### ISSUE TITLE
remove ; from jQuery function

### ISSUE THREAD

**Issue by dawjan** [vlucas/jscompress.com#6]
before minify:

**;**(function(e)

after minify:

(function(e)

So Js pareser get error:

Example file for conversion:

https://raw.githubusercontent.com/Schepp/CSS-Filters-Polyfill/gh-pages/lib/css-filters-polyfill.js

**Comment by vlucas** [comment]
Check out the new updated website: http://jscompress.com/ - it's a complete rewrite on React.js, and it solves a lot of outstanding issues.
